version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - pytorch_cpu
        - tensorflow
  system_packages: true

sphinx:
  fail_on_warning: true